### PR TITLE
Simplify function, explicitly name affected columns

### PR DESCRIPTION
**Pull request by pitkant**
My proposal to solve issue #38 

* Remove stringr dependency and use base R formatC instead
* remove for-loop, use apply instead
* explicitly name columns instead of using regular expressions
* Use Statistics Finland / Tilastokeskus conventions: some areas have a width of 3, some a width of 2 and some are just integers (from https://www2.tilastokeskus.fi/fi/luokitukset/ -> Alue)

Here is a list I compiled from Tilastokeskus website:

**Width 3**
municipality_code
kunta
seutukunta_code

**Width 2**
maakunta_code
ely_code
sairaanhoitop_code
tyossakayntial_code
vaalipiiri_code

**Integers**
kuntaryhmitys_code
kielisuhde_code
avi_code
suuralue_code

**?? (Probably integers)**
kela_vakuutuspiiri_code
kela_asumistukialue_code

### CODE REVIEW

**Comment by antagomir** [comment]
Looks great, ok to merge (from my side)!

**Comment by muuankarski** [comment]
Yes, this is exactly what I aimed at!

**Comment by muuankarski** [comment]
Yes, this is exactly what I aimed at!

**Review by muuankarski — COMMENTED** [review]
Yes, this is exactly what I aimed at!

**Pull request merged**
