### PR TITLE
Fix wellbeing services county codes & names, add 2022

### PR DESCRIPTION
**Pull request by pitkant**
- Changed some hard-coded well being county names in data.R to match the ones in Statistics Finland website
- Added support for downloading municipality classifications for year 2022

There's a catch though. I used 2021 as a template for 2022 as there were very little changes between the years. data.R script can download some classifications from stat.fi but not all. At least kuntaryhmitys, sairaanhoitop and similar information is missing at least for now.

Here are the differences between 2021 (75 variables) and 2022 (53 variables) if `municipality_key_2022` is created by running the script:

> `setdiff(names(municipality_key_2021), names(municipality_key_2022))`
> [1] "tyossakayntial_code"         "tyossakayntial_name_fi"      "sairaanhoitop_code"         
>  [4] "sairaanhoitop_name_fi"       "sairaanhoitop_name_sv"       "sairaanhoitop_name_en"      
>  [7] "kuntaryhmitys_code"          "kuntaryhmitys_name_fi"       "kuntaryhmitys_name_sv"      
> [10] "kuntaryhmitys_name_en"       "erva_code"                   "erva_name_fi"               
> [13] "erva_name_sv"                "erva_name_en"                "kela_vakuutuspiiri_name_fi" 
> [16] "kela_vakuutuspiiri_code"     "kela_vakuutuspiiri_name_sv"  "kela_vakuutuspiiri_name_en" 
> [19] "kela_asumistukialue_name_fi" "kela_asumistukialue_code"    "kela_asumistukialue_name_sv"
> [22] "kela_asumistukialue_name_en"

Source for wellbeing county classifications: https://www2.tilastokeskus.fi/fi/luokitukset/hyvinvointialue/
Statistics Finland classifications news bulletin: Changes in 2022: https://www2.stat.fi/fi/luokitukset/luokitustiedotteet/

### CODE REVIEW

**Comment by antagomir** [comment]
Seems good to me at least. Would be good if the main developer @muuankarski can confirm the merge though.

**Comment by muuankarski** [comment]
Great! stat.fi just introduced hyvinvointialueet to their classification api last week - They are supposed publish zipcode (paavo) data and updated the wfs-api with 2022 border, so I have waited for them to update it all.

As they only came up with the "official ones" now in January and the hand written ones have been there since summer 2021 using varnames `hyvinvointialue_name_*`, I am afraid we can't replace the same varname without breaking things at user end. Unfortunately stat.fi is using `hyvinvointialue` (not `hyvinvointial` for instance) in their api, so we have to manipulate it somehow. I mean, the new codes and new names are just different from the current, outdated ones.

On the other hand it would be so much more straighforward just to replace the old ones with the new ones. And just to apologize users for the inconvenience. (at least a lot of my recent code will break!!)

What do you think, to replace `hyvinvointialue_name_*/hyvinvointialue_code` with official ones, or to introduce the new as a separate var such as `statfi_hyvinvointialue_name_*/statfi_hyvinvointialue_code`?

**Comment by antagomir** [comment]
I would vote replacing with the official ones. But I am not the one who will fix the broken code, so it is easy to say. In the longer run that would be good, however.

**Comment by pitkant** [comment]
Maybe from a code maintenance point of view the simplest solution would be to introduce new statfi_hyvinvointialue_* variables and still have the old hyvinvointialue_name variables as well? Preferably with some intermediate plan for deprecating the other variable, maybe in 2023 edition?

**Comment by muuankarski** [comment]
I agree, I think we should do a cold blood replacement, try to inform users and encourage to test Github version. Perhaps also a note when loading the package that things have changed. Lot of people seem to draw hyvinvointialue maps in exact these days and some are using geofi!

**Comment by antagomir** [comment]
You can use the `.Deprecated` function (within your function), with a warning message. This will do the trick I guess, and it is more targeted than general startup message for the whole pkg.

**Pull request merged**
