### PR TITLE
added code for adjusted plot in png output

### PR DESCRIPTION
**Pull request by janikmiet**
Modified tricolore vignette so that plot is adjusted in png output.

### CODE REVIEW

**Comment by antagomir** [comment]
Automated checks fail. Is it possible to fix these before merging by some changes to Git Actions in 
.github/workflows$ less R-CMD-check.yaml

**Comment by janikmiet** [comment]
Package 'useful' seems to be a problem. Last part of vignette uses that package. Where this package import should be added to?

**Comment by antagomir** [comment]
I think, by some changes to Git Actions in .github/workflows/R-CMD-check.yaml file (this path starts from the root directory of the repo).

**Comment by janikmiet** [comment]
Now it passes. I added packages to DESCRIPTION suggestions part.

**Comment by antagomir** [comment]
Aah yeah of course. I was thinking too much..

Thanks!!

**Pull request merged**
